jdk:
- oraclejdk8
notifications:
  email: false
install:
- npm install
- pip install --user codecov
script:
- mvn verify
after_success:
- bash <(curl -s https://codecov.io/bash) -f ./target/site/jacoco-ut/jacoco.xml